export const availablesColors = [
  {name: 'Azul 1', class: 'azul-1', color: '#0033CC'},
  {name: 'Azul 2', class: 'azul-2', color: '#428BCA'},
  {name: 'Azul 3', class: 'azul-3', color: '#44AD8E'},
  {name: 'Verde 1', class: 'verde-1', color: '#A8D695'},
  {name: 'Verde 2', class: 'verde-2', color: '#5CB85C'},
  {name: 'Verde 3', class: 'verde-3', color: '#69D100'},
  {name: 'Verde 4', class: 'verde-4', color: '#004E00'},
  {name: 'Gris 1', class: 'gris-1', color: '#34495E'},
  {name: 'Gris 2', class: 'gris-2', color: '#7F8C8D'},
  {name: 'Gris 3', class: 'gris-3', color: '#A295D6'},
  {name: 'Morado 1', class: 'morado-1', color: '#5843AD'},
  {name: 'Morado 2', class: 'morado-2', color: '#8E44AD'},
  {name: 'Rojo 1', class: 'rojo-1', color: '#D10069'},
  {name: 'Rojo 2', class: 'rojo-2', color: '#CC0033'},
  {name: 'Rojo 3', class: 'rojo-3', color: '#FF0000'},
  {name: 'Rojo 4', class: 'rojo-4', color: '#D9534F'},
  {name: 'Amarillo 1', class: 'amarillo-1', color: '#D1D100'},
  {name: 'Amarillo 2', class: 'amarillo-2', color: '#F0AD4E'},
  {name: 'Amarillo 3', class: 'amarillo-3', color: '#AD8D43'},
];
